### PR TITLE
Add community files

### PR DESCRIPTION
**Pull request by xanjohns**
Add three basic community files:

- CONTRIBUTING.md
- CODE_OF_CONDUCT.md
- LICENSE

These files are adapted from those used by other SymbiFlow projects, but made to be generic for compatibility with all future repositories.

Signed-off-by: Xan Johnson <xanjohns@gmail.com>

### CODE REVIEW

**Comment by xanjohns** [comment]
@acomodi This pull request is ready for review as well.

**Comment by nelsobe** [comment]
@xanjohns @acomodi I would be interested to know once this PR is approved, will the next step be to apply the community files in this PR it to symbiflow-bram-patch?  I like that idea since that repo is one we created.  We can iterate with how the applying is done and then that will become the model for applying it to other repos.

**Review by acomodi — APPROVED** [review]
LGTM, merging

**Comment by acomodi** [comment]
@nelsobe @xanjohns Yes, I believe we can now proceed with getting this into the bram-patch repository and start the process of applying the community files in the various repos

**Pull request merged**
